// Adapter: Kiara's sanctions screening output (scrapers/sanctions/kyc_sanctions_flags.json)
// → two consumable shapes:
//   1) DIRECT hits — the screened name IS a KYC customer or one of its UBOs. These legitimately
//      drive the hard gate (CRITICAL / review per POLICY.sanctions). Today's data has none, but
//      the bridge handles them the moment they appear.
//   2) CONTAGION hits — a *linked entity* found in a customer's news is on a list. This is
//      counterparty exposure, NOT a direct identity match: it must NOT short-circuit the customer
//      to CRITICAL. It surfaces as a deterministic, cited risk signal on the linked customer and
//      as a red node in the Clusters graph.
//
// File shape: { generated_at, threshold, flags: [{ name, kind, contexts:[{linked_to, role,
//   dimension, title, url}], matches:[{score, matched_name, source, list_name, programs[]}] }] }
import { existsSync, readFileSync } from "node:fs";
import type { ClientBaseline, SignalScore } from "../types.js";
import { normName, type SanctionsHit } from "./sanctionsAdapter.js";
import { POLICY } from "../pipeline/policy.js";

interface FlagMatch {
  score?: number;
  matched_name?: string;
  source?: string;
  list_name?: string;
  programs?: string[];
}
interface FlagContext {
  linked_to?: string;
  role?: string;
  dimension?: string;
  title?: string;
  url?: string;
}
interface SanctionFlag {
  name: string;
  kind?: string; // "KYC company" | "Linked entity"
  contexts?: FlagContext[];
  matches?: FlagMatch[];
}

/** Counterparty-exposure hit, mapped to the customer it was linked to in the news. */
export interface ContagionFlag {
  entityName: string; // the sanctioned linked entity (as seen in the news)
  matchedName: string; // the sanctions-list record it matched
  score: number; // 0–100 fuzzy name-match score
  source: string; // OFAC / OpenSanctions / …
  listName: string; // e.g. "SDN List"
  programs: string[]; // sanctions programs (CUBA, SDGT, …)
  role: string; // how the entity is linked to the customer (from the article)
  url: string; // source article
  dimension: string; // drift dimension the article fell under
  tier: "confirmed" | "review"; // ≥ autoThreshold → confirmed; else human-review
}

export const DEFAULT_FLAGS_PATH = new URL(
  "../../../scrapers/sanctions/kyc_sanctions_flags.json",
  import.meta.url,
);

function readFlags(path: URL | string): SanctionFlag[] {
  if (!existsSync(path)) return []; // generated by scrapers/sanctions/kyc_check.py; absent until run
  const data = JSON.parse(readFileSync(path, "utf8")) as { flags?: SanctionFlag[] };
  return data.flags ?? [];
}

/** Highest-scoring match on a flag (the one we report). */
function bestMatch(flag: SanctionFlag): FlagMatch | undefined {
  return (flag.matches ?? []).slice().sort((a, b) => (b.score ?? 0) - (a.score ?? 0))[0];
}

/** Set of normalized customer + UBO names — used to tell direct hits from contagion. */
function ownNames(baselines: ClientBaseline[]): Set<string> {
  const own = new Set<string>();
  for (const b of baselines) {
    own.add(normName(b.legalName));
    for (const u of b.ubos) own.add(normName(u.name));
  }
  return own;
}

/**
 * DIRECT hits: the screened name is a KYC customer or UBO. Keyed by normalized name so the hard
 * gate's `querySanctions(name)` finds it. Empty if the file isn't generated.
 */
export function loadDirectSanctionsHits(
  baselines: ClientBaseline[],
  path: URL | string = DEFAULT_FLAGS_PATH,
): Map<string, SanctionsHit> {
  const map = new Map<string, SanctionsHit>();
  const own = ownNames(baselines);
  for (const flag of readFlags(path)) {
    const isDirect = flag.kind === "KYC company" || own.has(normName(flag.name));
    if (!isDirect) continue;
    const m = bestMatch(flag);
    if (!m) continue;
    map.set(normName(flag.name), {
      query: flag.name,
      matchedEntity: m.matched_name ?? flag.name,
      score: m.score ?? 100,
      source: m.source ?? "sanctions",
      programs: m.programs,
    });
  }
  return map;
}

/**
 * CONTAGION: a *linked entity* on a list, mapped to each customer it was linked to in the news.
 * Returns { clientId → ContagionFlag[] }. Direct hits are skipped (they go through the hard gate).
 */
export function loadContagionFlags(
  baselines: ClientBaseline[],
  path: URL | string = DEFAULT_FLAGS_PATH,
): Record<string, ContagionFlag[]> {
  const byLegalName = new Map<string, string>(); // normName(legalName) → clientId
  for (const b of baselines) byLegalName.set(normName(b.legalName), b.clientId);
  const own = ownNames(baselines);

  const out: Record<string, ContagionFlag[]> = {};
  for (const flag of readFlags(path)) {
    if (flag.kind === "KYC company" || own.has(normName(flag.name))) continue; // direct → hard gate
    const m = bestMatch(flag);
    if (!m) continue;
    const score = m.score ?? 0;
    const tier: ContagionFlag["tier"] = score >= POLICY.sanctions.autoThreshold ? "confirmed" : "review";
    const seen = new Set<string>(); // one entry per customer for this flag
    for (const ctx of flag.contexts ?? []) {
      const clientId = byLegalName.get(normName(ctx.linked_to ?? ""));
      if (!clientId || seen.has(clientId)) continue;
      seen.add(clientId);
      (out[clientId] ??= []).push({
        entityName: flag.name,
        matchedName: m.matched_name ?? flag.name,
        score,
        source: m.source ?? "sanctions",
        listName: m.list_name ?? "",
        programs: m.programs ?? [],
        role: ctx.role ?? "",
        url: ctx.url ?? "",
        dimension: ctx.dimension ?? "",
        tier,
      });
    }
  }
  return out;
}

/**
 * Turn a contagion hit into a DETERMINISTIC pre-scored signal. A sanctions-list match is a fact,
 * not an LLM judgement — so it bypasses the embedding gate / Stage-2 classifier entirely and is
 * fed straight into the composite score (mirroring the hard gate's determinism).
 */
export function contagionFlagToScore(c: ContagionFlag, i: number): SignalScore {
  const confirmed = c.tier === "confirmed";
  const programs = c.programs.length ? `; programs: ${c.programs.join(", ")}` : "";
  return {
    signalId: `sanction-contagion-${i}`,
    category: "sanctioned_counterparty",
    method: "rule_diff",
    magnitude: confirmed ? 80 : 45,
    direction: "risk_increasing",
    rationale:
      `Counterparty "${c.entityName}" appears on ${c.source} ${c.listName} ` +
      `(matched "${c.matchedName}", ${c.score}% name match${programs}). ` +
      `Linked to this client via: ${c.role || c.dimension || "news mention"}. ` +
      (confirmed
        ? "High-confidence match — sanctioned-counterparty exposure."
        : "Possible match below auto-block threshold — likely homonym; requires human verification."),
    suggestedAction: confirmed
      ? "Review the counterparty relationship; assess sanctions-policy breach and file a SAR if warranted."
      : "Verify counterparty identity (jurisdiction / LEI) before any action — clear the homonym or escalate.",
    sourceCitations: [c.url, `${c.source}: ${c.listName}`].filter(Boolean),
    confidence: confirmed ? 0.9 : 0.6,
    isFraudTypology: false,
  };
}
